# .staticman.yml
comments:
  allowedFields: ["name", "message", "slug", "permalink"]
  branch: "main"
  commitMessage: "Add comment by {fields.name} on {fields.slug}"
  filename: "comment-{date}"
  format: "yaml"
  moderation: true            # PRs for you to approve
  path: "blog/comments/{fields.slug}"
  requiredFields: ["name", "message", "slug"]
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
