backend:
  name: git-gateway
  branch: main

site_url: "https://peritumrecovery.com"

media_folder: "blog/postImages"     # MUST match your actual folder name/casing
public_folder: "/blog/postImages"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    format: "frontmatter"
    extension: "md"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}/"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }

      - label: "Publish Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"

      - { label: "Author", name: "author", widget: "string", default: "Peritum Recovery Team" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text", hint: "Short summary for blog listing & SEO" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["crypto", "recovery"] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }

      # Make sure every new post has your Eleventy layout
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog/_includes/layouts/post.njk" }
